package com.example.perraco.Objets

data class Urls(
    var url:String,
    var endPointInventario:String,
    var endPointImagenes:String,
    var endpointObtenerFamilias:String,
    var endpointObtenerSubFamilias:String,
    var endpointObtenerSubFamilia:String,
    var endpointDarAltaArticulo:String,
    var endpointSubirImagen:String,
    var endPointArticulo:String,
    var endPointVenta:String,
    var endPointObtenerVentas:String,
    var endPointAgregarFamilia:String,
    var endPointAgregarSubFamilia:String,
    var endPointEliminarFamilia:String,
    var endPointEliminarSubFamilia:String,
    var endPointActualizarArticulo:String,
    var endPointEliminarArticulo:String,
    var endPointEliminarVenta:String,
    var endPointActualizarVenta:String,
    var endPointLoginUsuario:String,
    var endPointRegistrarNuevaTienda:String,
    var endPointArticulosPorFamilia:String,
    var endPointArticulosPorSubFamilia:String,
    var endPointBuscarVentaPorFecha:String,
    var endPointArticulosMasVendidos:String,
    var endPointEstadisticasPorFecha:String,
    var endPointEstadisticasInventario:String,
    var endPointActualizarInventario:String,
    var endPointConsultarFamiliasSubFamilias:String)
{
    constructor(): this(
        "https://tienditaplus.herokuapp.com/",
        /*"http://pvgestordeinventario-env.eba-p2bc44jy.us-east-1.elasticbeanstalk.com/",*/
        "inventario/obtenerInventario",
        "imagenes/obtenerImagen?image=",
        "familias/consultarFamilias",
        "familias/consultarSubFamilias",
        "familias/consultarSubFamilia",
        "inventario/darAltaArticulo",
        "imagenes/subirImagen",
        "inventario/obtenerArticuloInventario",
        "ventas/darAltaVenta",
        "ventas/obtenerVentas",
        "familias/agregarFamilia",
        "familias/agregarSubFamilia",
        "familias/eliminarFamilia",
        "familias/eliminarSubFamilia",
        "inventario/actualizarArticulo",
        "inventario/eliminarArticulo",
        "ventas/eliminarVenta",
        "ventas/actualizarVenta",
        "users/loginUsuario",
        "users/registrarNuevaTienda",
        "inventario/buscarArticulosPorFamilia",
        "inventario/buscarArticulosPorSubFamilia",
        "ventas/buscarVentaPorFecha",
        "estadisticas/buscarArticulosMasVendidos",
        "ventas/estadisticasPorFecha",
        "estadisticas/obtenerTotalInventario",
        "inventario/actualizarInventario",
        "familias/consultarFamiliasSubFamilias")

}
